import uuid
from datetime import datetime
from sqlalchemy import String, Float, Integer, Boolean, DateTime, ForeignKey, JSON, Text, Index, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base, TimestampMixin


class AttendanceAttempt(Base, TimestampMixin):
    """
    Every biometric scan attempt is stored here — success or failure.
    This is the raw event log. The official attendance status lives in AttendanceRecord.

    Attempt statuses:
        VERIFIED, FACE_FAILED, LIVENESS_FAILED, LOCATION_FAILED,
        GPS_FAILED, DEVICE_INVALID, PENDING_REVIEW
    """
    __tablename__ = "attendance_attempts"
    __table_args__ = (
        UniqueConstraint("client_event_id", name="uq_attendance_attempt_event_id"),
        Index("ix_att_attempt_user_date", "user_id", "server_received_at"),
        Index("ix_att_attempt_status", "status"),
        Index("ix_att_attempt_org_date", "organization_id", "server_received_at"),
        Index("ix_att_attempt_location", "location_id"),
        Index("ix_att_attempt_device", "device_id"),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    # Idempotency key — generated by the mobile app
    client_event_id: Mapped[str] = mapped_column(String(100), unique=True, nullable=False, index=True)

    organization_id: Mapped[str] = mapped_column(String(36), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id: Mapped[str] = mapped_column(String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=False, index=True)
    device_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("devices.id", ondelete="SET NULL"))
    assignment_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("assignments.id", ondelete="SET NULL"))
    project_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("projects.id", ondelete="SET NULL"))
    location_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("locations.id", ondelete="SET NULL"))
    shift_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("shifts.id", ondelete="SET NULL"))

    # Event metadata
    event_type: Mapped[str] = mapped_column(String(20), default="CHECK_IN", nullable=False)  # CHECK_IN | CHECK_OUT
    attempt_number: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    # Timestamps
    client_timestamp: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    server_received_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    device_clock_offset_seconds: Mapped[float | None] = mapped_column(Float)

    # GPS
    latitude: Mapped[float | None] = mapped_column(Float)
    longitude: Mapped[float | None] = mapped_column(Float)
    gps_accuracy_meters: Mapped[float | None] = mapped_column(Float)
    distance_from_site_meters: Mapped[float | None] = mapped_column(Float)  # server-calculated

    # Biometric results (from mobile)
    face_verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    face_score: Mapped[float | None] = mapped_column(Float)
    liveness_verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    liveness_score: Mapped[float | None] = mapped_column(Float)

    # Location verdict (server-calculated)
    location_verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Offline metadata
    offline_created: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    network_type: Mapped[str | None] = mapped_column(String(20))
    battery_level: Mapped[int | None] = mapped_column(Integer)

    # Result
    # Statuses: VERIFIED, FACE_FAILED, LIVENESS_FAILED, LOCATION_FAILED,
    #           GPS_FAILED, DEVICE_INVALID, PENDING_REVIEW
    status: Mapped[str] = mapped_column(String(30), nullable=False, index=True)
    failure_reason: Mapped[str | None] = mapped_column(Text)

    # Fraud signals
    risk_flags: Mapped[list | None] = mapped_column(JSON)

    # Cryptographic event signature
    event_signature: Mapped[str | None] = mapped_column(Text)
    signature_algorithm: Mapped[str | None] = mapped_column(String(30))

    # Arbitrary metadata
    metadata_: Mapped[dict | None] = mapped_column("metadata", JSON)

    # Relationships
    user: Mapped["User"] = relationship(back_populates="attendance_attempts")
    assignment: Mapped["Assignment"] = relationship(back_populates="attendance_attempts")
