"""Attendance schemas matching Flutter AttendanceApi and AttendanceRecord model."""
from datetime import datetime
from pydantic import BaseModel, Field, field_validator
from app.schemas.common import OrmModel


# ─── Attempt Request (from mobile) ───────────────────────────────────────────

class AttendanceAttemptCreate(BaseModel):
    """Sent by Flutter AttendanceApi.markAttendance() / runVerification()."""
    client_event_id: str = Field(..., description="Idempotency key — UUID generated by mobile")
    event_type: str = Field(default="CHECK_IN", pattern="^(CHECK_IN|CHECK_OUT)$")

    # Timestamps
    client_timestamp: datetime | None = None

    # GPS — may be None if offline and GPS unavailable
    latitude: float | None = Field(default=None, ge=-90, le=90)
    longitude: float | None = Field(default=None, ge=-180, le=180)
    gps_accuracy_meters: float | None = Field(default=None, ge=0)

    # Biometric results from on-device processing
    face_verified: bool = False
    face_score: float | None = Field(default=None, ge=0, le=1)
    liveness_verified: bool = False
    liveness_score: float | None = Field(default=None, ge=0, le=1)

    # Offline metadata
    offline_created: bool = False
    network_type: str | None = None
    battery_level: int | None = Field(default=None, ge=0, le=100)

    # Optional cryptographic signature (future)
    event_signature: str | None = None
    signature_algorithm: str | None = None


# ─── Attempt Response ─────────────────────────────────────────────────────────

class AttendanceAttemptOut(OrmModel):
    """Returned after processing an attendance attempt."""
    id: str
    client_event_id: str
    status: str
    event_type: str
    face_verified: bool
    face_score: float | None
    liveness_verified: bool
    liveness_score: float | None
    location_verified: bool
    distance_from_site_meters: float | None
    gps_accuracy_meters: float | None
    failure_reason: str | None
    risk_flags: list[str] | None
    server_received_at: datetime
    attendance_record_id: str | None = None


# ─── Attendance Record Response ───────────────────────────────────────────────

class AttendanceRecordOut(OrmModel):
    """Matches Flutter AttendanceRecord domain model."""
    id: str
    attendance_date: str           # ISO date string
    status: str
    check_in_time: datetime | None
    check_out_time: datetime | None
    assigned_site: str | None = None
    distance_meters: int | None = None
    face_status: str
    liveness_status: str
    location_status: str
    sync_status: str = "SYNCED"
    remarks: str | None = None
    face_score: float | None
    liveness_score: float | None
    gps_accuracy: int | None = None
    work_duration_minutes: float | None = None


# ─── Admin Filters ────────────────────────────────────────────────────────────

class AttendanceAdminFilters(BaseModel):
    date_from: str | None = None
    date_to: str | None = None
    employee_id: str | None = None
    department_id: str | None = None
    project_id: str | None = None
    location_id: str | None = None
    shift_id: str | None = None
    status: str | None = None
